name: 'Go Test Split'
author: 'Brandon Croft'
description: >
  Given some splitting parameters (total slices and slice index), lists a subset of tests
  suitable for passing into go test -run.
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  total:
    description: "The total number of slices that will be generated"
    required: true
    default: "1"
  index:
    description: "The zero-based index of the current slice to generate"
    required: true
    default: "0"
  packages:
    description: "The packages string to use when executing `go test <packages> -list .` to find tests. Defaults to './...' (all packages recursively)"
    required: false
  list:
    description: "The list pattern to use when executing `go test <packages> -list <list>`. Defaults to '.' (all tests)"
    required: false
  flags:
    description: "Additional flags to pass to `go test <packages> -list ."
    required: false
  junit-summary:
    description: "Path to a JUnit summary XML file that can help optimize test slicing. See the JUnit example in the README."
    required: false
  working-directory:
    description: "The working directory in which to list the tests. Defaults to the GitHub workspace."
    required: false
outputs:
  run:
    description: "A slice of tests, suitable to pass into the -run argument of go test"
