name: lint-test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: "ubuntu-latest"
    name: "Run"
    steps:
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          go-version: 1.19
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: npm

      - name: npm ci
        run: npm ci

      - name: Format Check
        run: npm run format-check

      - name: Verify
        run: |
          npm run build
          # Fail if "npm run build" generated new changes in dist
          git update-index --refresh dist/* && git diff-index --quiet HEAD dist

      - name: Test
        run: npm run test
